[profile.default]
src = "contracts"
test = "test/foundry"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "cancun"
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 100
gas_reports = ["Roles"]

[profile.default.fmt]
line_length = 100
