[profile.default]
src = "contracts"
test = "foundry-test"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.17"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@gnosis-guild/zodiac-core/=node_modules/@gnosis-guild/zodiac-core/"
]
